validates:
  maximum_name: 50
  maximum_email: 255
  minimum_password: 6
  max_length_content_micropost: 140
  img_micropost_size: 5
gravatar_size: 80
gravatar_user_size: 50
show_gravatar_size: 30
remember_me: "1"
index_page: 15
password_reset_expired: 2
upload_resize_to_limit: 400
micropost_per_page: 10
resize_to_limit: 400
mime_picture: "image/jpeg,image/gif,image/png"
following_per_page: 10
followers_per_page: 10

